/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.client;

import com.mastercard.api.places.ApiException;
import com.mastercard.api.places.model.ErrorResponse;
import com.mastercard.api.places.model.MerchantIndustryCode;
import com.mastercard.api.places.model.PagedMerchantIndustryCode;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MerchantIndustryCodesApi
 */
@Ignore
public class MerchantIndustryCodesApiTest {

    private final MerchantIndustryCodesApi api = new MerchantIndustryCodesApi();

    
    /**
     * Get all active merchant industry codes
     *
     * Returns a list of Merchant Industries ordered by Merchant Industry Codes or Merchant Industry Name depending on user input. The list will be ordered by Merchant Industry Name by default.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllIndustryCodesUsingGETTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String sort = null;
                PagedMerchantIndustryCode response = api.getAllIndustryCodesUsingGET(limit, offset, sort);
        // TODO: test validations
    }
    
    /**
     * Get merchant industry code details by industry code
     *
     * Returns Merchant Industry code details by  Industry code
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByIndustryUsingGETTest() throws ApiException {
        String industry = null;
                MerchantIndustryCode response = api.getByIndustryUsingGET(industry);
        // TODO: test validations
    }
    
}
