/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.client;

import com.mastercard.api.places.ApiException;
import com.mastercard.api.places.model.ErrorResponse;
import com.mastercard.api.places.model.PagedPlaceInfo;
import com.mastercard.api.places.model.PlaceInfo;
import com.mastercard.api.places.model.PlaceSearchRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlacesApi
 */
@Ignore
public class PlacesApiTest {

    private final PlacesApi api = new PlacesApi();

    
    /**
     * Get the location details by using location id
     *
     * Returns detailed information on merchants based on the provided, query parameter, locationId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlaceByLocationIdUsingGETTest() throws ApiException {
        Long locationId = null;
                PlaceInfo response = api.getPlaceByLocationIdUsingGET(locationId);
        // TODO: test validations
    }
    
    /**
     * Search for places 
     *
     * Returns detailed information on merchants based on the provided, query parameter
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchPlacesUsingPOSTTest() throws ApiException {
        PlaceSearchRequest placeSearchRequest = null;
        Integer limit = null;
        Integer offset = null;
                PagedPlaceInfo response = api.searchPlacesUsingPOST(placeSearchRequest, limit, offset);
        // TODO: test validations
    }
    
}
