/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MerchantIndustryCode
 */
public class MerchantIndustryCodeTest {
    private final MerchantIndustryCode model = new MerchantIndustryCode();

    /**
     * Model tests for MerchantIndustryCode
     */
    @Test
    public void testMerchantIndustryCode() {
        // TODO: test MerchantIndustryCode
    }

    /**
     * Test the property 'industry'
     */
    @Test
    public void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'industryName'
     */
    @Test
    public void industryNameTest() {
        // TODO: test industryName
    }

}
