/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MerchantCategoryCode
 */
public class MerchantCategoryCodeTest {
    private final MerchantCategoryCode model = new MerchantCategoryCode();

    /**
     * Model tests for MerchantCategoryCode
     */
    @Test
    public void testMerchantCategoryCode() {
        // TODO: test MerchantCategoryCode
    }

    /**
     * Test the property 'merchantCategoryCode'
     */
    @Test
    public void merchantCategoryCodeTest() {
        // TODO: test merchantCategoryCode
    }

    /**
     * Test the property 'merchantCategoryName'
     */
    @Test
    public void merchantCategoryNameTest() {
        // TODO: test merchantCategoryName
    }

}
