/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.places.model.PlaceFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlaceSearchRequest
 */
public class PlaceSearchRequestTest {
    private final PlaceSearchRequest model = new PlaceSearchRequest();

    /**
     * Model tests for PlaceSearchRequest
     */
    @Test
    public void testPlaceSearchRequest() {
        // TODO: test PlaceSearchRequest
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'place'
     */
    @Test
    public void placeTest() {
        // TODO: test place
    }

    /**
     * Test the property 'radiusSearch'
     */
    @Test
    public void radiusSearchTest() {
        // TODO: test radiusSearch
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
