/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlaceFilter
 */
public class PlaceFilterTest {
    private final PlaceFilter model = new PlaceFilter();

    /**
     * Model tests for PlaceFilter
     */
    @Test
    public void testPlaceFilter() {
        // TODO: test PlaceFilter
    }

    /**
     * Test the property 'aggregateMerchantId'
     */
    @Test
    public void aggregateMerchantIdTest() {
        // TODO: test aggregateMerchantId
    }

    /**
     * Test the property 'aggregateMerchantName'
     */
    @Test
    public void aggregateMerchantNameTest() {
        // TODO: test aggregateMerchantName
    }

    /**
     * Test the property 'cityName'
     */
    @Test
    public void cityNameTest() {
        // TODO: test cityName
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'dmaCode'
     */
    @Test
    public void dmaCodeTest() {
        // TODO: test dmaCode
    }

    /**
     * Test the property 'geocodeQualityIndicator'
     */
    @Test
    public void geocodeQualityIndicatorTest() {
        // TODO: test geocodeQualityIndicator
    }

    /**
     * Test the property 'hasCashBack'
     */
    @Test
    public void hasCashBackTest() {
        // TODO: test hasCashBack
    }

    /**
     * Test the property 'hasNfc'
     */
    @Test
    public void hasNfcTest() {
        // TODO: test hasNfc
    }

    /**
     * Test the property 'hasPayAtThePump'
     */
    @Test
    public void hasPayAtThePumpTest() {
        // TODO: test hasPayAtThePump
    }

    /**
     * Test the property 'industry'
     */
    @Test
    public void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'isInBusiness180Day'
     */
    @Test
    public void isInBusiness180DayTest() {
        // TODO: test isInBusiness180Day
    }

    /**
     * Test the property 'isInBusiness30Day'
     */
    @Test
    public void isInBusiness30DayTest() {
        // TODO: test isInBusiness30Day
    }

    /**
     * Test the property 'isInBusiness360Day'
     */
    @Test
    public void isInBusiness360DayTest() {
        // TODO: test isInBusiness360Day
    }

    /**
     * Test the property 'isInBusiness60Day'
     */
    @Test
    public void isInBusiness60DayTest() {
        // TODO: test isInBusiness60Day
    }

    /**
     * Test the property 'isInBusiness7Day'
     */
    @Test
    public void isInBusiness7DayTest() {
        // TODO: test isInBusiness7Day
    }

    /**
     * Test the property 'isInBusiness90Day'
     */
    @Test
    public void isInBusiness90DayTest() {
        // TODO: test isInBusiness90Day
    }

    /**
     * Test the property 'isNewBusiness'
     */
    @Test
    public void isNewBusinessTest() {
        // TODO: test isNewBusiness
    }

    /**
     * Test the property 'keyAggregateMerchantId'
     */
    @Test
    public void keyAggregateMerchantIdTest() {
        // TODO: test keyAggregateMerchantId
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'legalCorporateName'
     */
    @Test
    public void legalCorporateNameTest() {
        // TODO: test legalCorporateName
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'mccCode'
     */
    @Test
    public void mccCodeTest() {
        // TODO: test mccCode
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'msaCode'
     */
    @Test
    public void msaCodeTest() {
        // TODO: test msaCode
    }

    /**
     * Test the property 'naicsCode'
     */
    @Test
    public void naicsCodeTest() {
        // TODO: test naicsCode
    }

    /**
     * Test the property 'parentAggregateMerchantId'
     */
    @Test
    public void parentAggregateMerchantIdTest() {
        // TODO: test parentAggregateMerchantId
    }

    /**
     * Test the property 'parentAggregateMerchantName'
     */
    @Test
    public void parentAggregateMerchantNameTest() {
        // TODO: test parentAggregateMerchantName
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'primaryChannelOfDistribution'
     */
    @Test
    public void primaryChannelOfDistributionTest() {
        // TODO: test primaryChannelOfDistribution
    }

    /**
     * Test the property 'stateProvinceCode'
     */
    @Test
    public void stateProvinceCodeTest() {
        // TODO: test stateProvinceCode
    }

    /**
     * Test the property 'streetAddress'
     */
    @Test
    public void streetAddressTest() {
        // TODO: test streetAddress
    }

    /**
     * Test the property 'superIndustry'
     */
    @Test
    public void superIndustryTest() {
        // TODO: test superIndustry
    }

    /**
     * Test the property 'telephoneNumber'
     */
    @Test
    public void telephoneNumberTest() {
        // TODO: test telephoneNumber
    }

}
