/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Merchant Industry Code
 */
@ApiModel(description = "Merchant Industry Code")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-10T10:46:25.143944500-05:00[America/Chicago]")
public class MerchantIndustryCode {
  public static final String SERIALIZED_NAME_INDUSTRY = "industry";
  @SerializedName(SERIALIZED_NAME_INDUSTRY)
  private String industry;

  public static final String SERIALIZED_NAME_INDUSTRY_NAME = "industryName";
  @SerializedName(SERIALIZED_NAME_INDUSTRY_NAME)
  private String industryName;


  public MerchantIndustryCode industry(String industry) {
    
    this.industry = industry;
    return this;
  }

   /**
   * This code represents the industry that a merchant location may be under and is supported by most payments providers
   * @return industry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ACC", value = "This code represents the industry that a merchant location may be under and is supported by most payments providers")

  public String getIndustry() {
    return industry;
  }


  public void setIndustry(String industry) {
    this.industry = industry;
  }


  public MerchantIndustryCode industryName(String industryName) {
    
    this.industryName = industryName;
    return this;
  }

   /**
   * This is the name of the Industry that accompanies the Industry Code which identifies the industry a merchant falls under
   * @return industryName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Accommodations", value = "This is the name of the Industry that accompanies the Industry Code which identifies the industry a merchant falls under")

  public String getIndustryName() {
    return industryName;
  }


  public void setIndustryName(String industryName) {
    this.industryName = industryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantIndustryCode merchantIndustryCode = (MerchantIndustryCode) o;
    return Objects.equals(this.industry, merchantIndustryCode.industry) &&
        Objects.equals(this.industryName, merchantIndustryCode.industryName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(industry, industryName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantIndustryCode {\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    industryName: ").append(toIndentedString(industryName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

