/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.api.places.model.MerchantIndustryCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Paged response of Merchant Industry Codes
 */
@ApiModel(description = "Paged response of Merchant Industry Codes")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-10T10:46:25.143944500-05:00[America/Chicago]")
public class PagedMerchantIndustryCodeAllOf {
  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<MerchantIndustryCode> items = new ArrayList<MerchantIndustryCode>();


  public PagedMerchantIndustryCodeAllOf items(List<MerchantIndustryCode> items) {
    
    this.items = items;
    return this;
  }

  public PagedMerchantIndustryCodeAllOf addItemsItem(MerchantIndustryCode itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Array of Merchant Industry Codes
   * @return items
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Array of Merchant Industry Codes")

  public List<MerchantIndustryCode> getItems() {
    return items;
  }


  public void setItems(List<MerchantIndustryCode> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedMerchantIndustryCodeAllOf pagedMerchantIndustryCodeAllOf = (PagedMerchantIndustryCodeAllOf) o;
    return Objects.equals(this.items, pagedMerchantIndustryCodeAllOf.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedMerchantIndustryCodeAllOf {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

