/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Place Info
 */
@ApiModel(description = "Place Info")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-10T10:46:25.143944500-05:00[America/Chicago]")
public class PlaceInfo {
  public static final String SERIALIZED_NAME_AGGREGATE_MERCHANT_ID = "aggregateMerchantId";
  @SerializedName(SERIALIZED_NAME_AGGREGATE_MERCHANT_ID)
  private Long aggregateMerchantId;

  public static final String SERIALIZED_NAME_AGGREGATE_MERCHANT_NAME = "aggregateMerchantName";
  @SerializedName(SERIALIZED_NAME_AGGREGATE_MERCHANT_NAME)
  private String aggregateMerchantName;

  public static final String SERIALIZED_NAME_CITY_NAME = "cityName";
  @SerializedName(SERIALIZED_NAME_CITY_NAME)
  private String cityName;

  public static final String SERIALIZED_NAME_CLEANSED_CITY_NAME = "cleansedCityName";
  @SerializedName(SERIALIZED_NAME_CLEANSED_CITY_NAME)
  private String cleansedCityName;

  public static final String SERIALIZED_NAME_CLEANSED_COUNTRY_CODE = "cleansedCountryCode";
  @SerializedName(SERIALIZED_NAME_CLEANSED_COUNTRY_CODE)
  private String cleansedCountryCode;

  public static final String SERIALIZED_NAME_CLEANSED_LEGAL_CORPORATE_NAME = "cleansedLegalCorporateName";
  @SerializedName(SERIALIZED_NAME_CLEANSED_LEGAL_CORPORATE_NAME)
  private String cleansedLegalCorporateName;

  public static final String SERIALIZED_NAME_CLEANSED_MERCHANT_NAME = "cleansedMerchantName";
  @SerializedName(SERIALIZED_NAME_CLEANSED_MERCHANT_NAME)
  private String cleansedMerchantName;

  public static final String SERIALIZED_NAME_CLEANSED_POSTAL_CODE = "cleansedPostalCode";
  @SerializedName(SERIALIZED_NAME_CLEANSED_POSTAL_CODE)
  private String cleansedPostalCode;

  public static final String SERIALIZED_NAME_CLEANSED_STATE_PROVINCE_CODE = "cleansedStateProvinceCode";
  @SerializedName(SERIALIZED_NAME_CLEANSED_STATE_PROVINCE_CODE)
  private String cleansedStateProvinceCode;

  public static final String SERIALIZED_NAME_CLEANSED_STREET_ADDRESS = "cleansedStreetAddress";
  @SerializedName(SERIALIZED_NAME_CLEANSED_STREET_ADDRESS)
  private String cleansedStreetAddress;

  public static final String SERIALIZED_NAME_CLEANSED_TELEPHONE_NUMBER = "cleansedTelephoneNumber";
  @SerializedName(SERIALIZED_NAME_CLEANSED_TELEPHONE_NUMBER)
  private String cleansedTelephoneNumber;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_FIRST_SEEN_WEEK = "firstSeenWeek";
  @SerializedName(SERIALIZED_NAME_FIRST_SEEN_WEEK)
  private String firstSeenWeek;

  public static final String SERIALIZED_NAME_LAST_SEEN_WEEK = "lastSeenWeek";
  @SerializedName(SERIALIZED_NAME_LAST_SEEN_WEEK)
  private String lastSeenWeek;

  public static final String SERIALIZED_NAME_DMA_CODE = "dmaCode";
  @SerializedName(SERIALIZED_NAME_DMA_CODE)
  private String dmaCode;

  public static final String SERIALIZED_NAME_GEOCODE_QUALITY_INDICATOR = "geocodeQualityIndicator";
  @SerializedName(SERIALIZED_NAME_GEOCODE_QUALITY_INDICATOR)
  private String geocodeQualityIndicator;

  public static final String SERIALIZED_NAME_HAS_CASH_BACK = "hasCashBack";
  @SerializedName(SERIALIZED_NAME_HAS_CASH_BACK)
  private Boolean hasCashBack;

  public static final String SERIALIZED_NAME_HAS_NFC = "hasNfc";
  @SerializedName(SERIALIZED_NAME_HAS_NFC)
  private Boolean hasNfc;

  public static final String SERIALIZED_NAME_HAS_PAY_AT_THE_PUMP = "hasPayAtThePump";
  @SerializedName(SERIALIZED_NAME_HAS_PAY_AT_THE_PUMP)
  private Boolean hasPayAtThePump;

  public static final String SERIALIZED_NAME_INDUSTRY = "industry";
  @SerializedName(SERIALIZED_NAME_INDUSTRY)
  private String industry;

  public static final String SERIALIZED_NAME_IS_IN_BUSINESS180_DAY = "isInBusiness180Day";
  @SerializedName(SERIALIZED_NAME_IS_IN_BUSINESS180_DAY)
  private Boolean isInBusiness180Day;

  public static final String SERIALIZED_NAME_IS_IN_BUSINESS30_DAY = "isInBusiness30Day";
  @SerializedName(SERIALIZED_NAME_IS_IN_BUSINESS30_DAY)
  private Boolean isInBusiness30Day;

  public static final String SERIALIZED_NAME_IS_IN_BUSINESS360_DAY = "isInBusiness360Day";
  @SerializedName(SERIALIZED_NAME_IS_IN_BUSINESS360_DAY)
  private Boolean isInBusiness360Day;

  public static final String SERIALIZED_NAME_IS_IN_BUSINESS60_DAY = "isInBusiness60Day";
  @SerializedName(SERIALIZED_NAME_IS_IN_BUSINESS60_DAY)
  private Boolean isInBusiness60Day;

  public static final String SERIALIZED_NAME_IS_IN_BUSINESS7_DAY = "isInBusiness7Day";
  @SerializedName(SERIALIZED_NAME_IS_IN_BUSINESS7_DAY)
  private Boolean isInBusiness7Day;

  public static final String SERIALIZED_NAME_IS_IN_BUSINESS90_DAY = "isInBusiness90Day";
  @SerializedName(SERIALIZED_NAME_IS_IN_BUSINESS90_DAY)
  private Boolean isInBusiness90Day;

  public static final String SERIALIZED_NAME_IS_NEW_BUSINESS = "isNewBusiness";
  @SerializedName(SERIALIZED_NAME_IS_NEW_BUSINESS)
  private Boolean isNewBusiness;

  public static final String SERIALIZED_NAME_KEY_AGGREGATE_MERCHANT_ID = "keyAggregateMerchantId";
  @SerializedName(SERIALIZED_NAME_KEY_AGGREGATE_MERCHANT_ID)
  private Long keyAggregateMerchantId;

  public static final String SERIALIZED_NAME_LATITUDE = "latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private Double latitude;

  public static final String SERIALIZED_NAME_LEGAL_CORPORATE_NAME = "legalCorporateName";
  @SerializedName(SERIALIZED_NAME_LEGAL_CORPORATE_NAME)
  private String legalCorporateName;

  public static final String SERIALIZED_NAME_LOCATION_ID = "locationId";
  @SerializedName(SERIALIZED_NAME_LOCATION_ID)
  private Long locationId;

  public static final String SERIALIZED_NAME_LONGITUDE = "longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private Double longitude;

  public static final String SERIALIZED_NAME_MCC_CODE = "mccCode";
  @SerializedName(SERIALIZED_NAME_MCC_CODE)
  private String mccCode;

  public static final String SERIALIZED_NAME_MERCHANT_NAME = "merchantName";
  @SerializedName(SERIALIZED_NAME_MERCHANT_NAME)
  private String merchantName;

  public static final String SERIALIZED_NAME_MSA_CODE = "msaCode";
  @SerializedName(SERIALIZED_NAME_MSA_CODE)
  private String msaCode;

  public static final String SERIALIZED_NAME_NAICS_CODE = "naicsCode";
  @SerializedName(SERIALIZED_NAME_NAICS_CODE)
  private String naicsCode;

  public static final String SERIALIZED_NAME_PARENT_AGGREGATE_MERCHANT_ID = "parentAggregateMerchantId";
  @SerializedName(SERIALIZED_NAME_PARENT_AGGREGATE_MERCHANT_ID)
  private String parentAggregateMerchantId;

  public static final String SERIALIZED_NAME_PARENT_AGGREGATE_MERCHANT_NAME = "parentAggregateMerchantName";
  @SerializedName(SERIALIZED_NAME_PARENT_AGGREGATE_MERCHANT_NAME)
  private String parentAggregateMerchantName;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_PRIMARY_CHANNEL_OF_DISTRIBUTION = "primaryChannelOfDistribution";
  @SerializedName(SERIALIZED_NAME_PRIMARY_CHANNEL_OF_DISTRIBUTION)
  private String primaryChannelOfDistribution;

  public static final String SERIALIZED_NAME_STATE_PROVINCE_CODE = "stateProvinceCode";
  @SerializedName(SERIALIZED_NAME_STATE_PROVINCE_CODE)
  private String stateProvinceCode;

  public static final String SERIALIZED_NAME_STREET_ADDRESS = "streetAddress";
  @SerializedName(SERIALIZED_NAME_STREET_ADDRESS)
  private String streetAddress;

  public static final String SERIALIZED_NAME_SUPER_INDUSTRY = "superIndustry";
  @SerializedName(SERIALIZED_NAME_SUPER_INDUSTRY)
  private String superIndustry;

  public static final String SERIALIZED_NAME_TELEPHONE_NUMBER = "telephoneNumber";
  @SerializedName(SERIALIZED_NAME_TELEPHONE_NUMBER)
  private String telephoneNumber;


  public PlaceInfo aggregateMerchantId(Long aggregateMerchantId) {
    
    this.aggregateMerchantId = aggregateMerchantId;
    return this;
  }

   /**
   * Merchant Aggregate ID groups merchant locations by chain. This is the first level of aggregation
   * @return aggregateMerchantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12077", value = "Merchant Aggregate ID groups merchant locations by chain. This is the first level of aggregation")

  public Long getAggregateMerchantId() {
    return aggregateMerchantId;
  }


  public void setAggregateMerchantId(Long aggregateMerchantId) {
    this.aggregateMerchantId = aggregateMerchantId;
  }


  public PlaceInfo aggregateMerchantName(String aggregateMerchantName) {
    
    this.aggregateMerchantName = aggregateMerchantName;
    return this;
  }

   /**
   * The aggregate merchant name of this merchant location
   * @return aggregateMerchantName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FAMOUS FOOTWEAR", value = "The aggregate merchant name of this merchant location")

  public String getAggregateMerchantName() {
    return aggregateMerchantName;
  }


  public void setAggregateMerchantName(String aggregateMerchantName) {
    this.aggregateMerchantName = aggregateMerchantName;
  }


  public PlaceInfo cityName(String cityName) {
    
    this.cityName = cityName;
    return this;
  }

   /**
   * The city for the desired location
   * @return cityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "O FALLON", value = "The city for the desired location")

  public String getCityName() {
    return cityName;
  }


  public void setCityName(String cityName) {
    this.cityName = cityName;
  }


  public PlaceInfo cleansedCityName(String cleansedCityName) {
    
    this.cleansedCityName = cleansedCityName;
    return this;
  }

   /**
   * The cleansed city name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedCityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "O FALLON", value = "The cleansed city name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedCityName() {
    return cleansedCityName;
  }


  public void setCleansedCityName(String cleansedCityName) {
    this.cleansedCityName = cleansedCityName;
  }


  public PlaceInfo cleansedCountryCode(String cleansedCountryCode) {
    
    this.cleansedCountryCode = cleansedCountryCode;
    return this;
  }

   /**
   * The cleansed country code is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedCountryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "US", value = "The cleansed country code is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedCountryCode() {
    return cleansedCountryCode;
  }


  public void setCleansedCountryCode(String cleansedCountryCode) {
    this.cleansedCountryCode = cleansedCountryCode;
  }


  public PlaceInfo cleansedLegalCorporateName(String cleansedLegalCorporateName) {
    
    this.cleansedLegalCorporateName = cleansedLegalCorporateName;
    return this;
  }

   /**
   * The cleansed legal corporate name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedLegalCorporateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "BROWN SHOE COMPANY INC", value = "The cleansed legal corporate name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedLegalCorporateName() {
    return cleansedLegalCorporateName;
  }


  public void setCleansedLegalCorporateName(String cleansedLegalCorporateName) {
    this.cleansedLegalCorporateName = cleansedLegalCorporateName;
  }


  public PlaceInfo cleansedMerchantName(String cleansedMerchantName) {
    
    this.cleansedMerchantName = cleansedMerchantName;
    return this;
  }

   /**
   * The cleansed merchant name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedMerchantName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FAMOUS FOOTWEAR #1749", value = "The cleansed merchant name is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedMerchantName() {
    return cleansedMerchantName;
  }


  public void setCleansedMerchantName(String cleansedMerchantName) {
    this.cleansedMerchantName = cleansedMerchantName;
  }


  public PlaceInfo cleansedPostalCode(String cleansedPostalCode) {
    
    this.cleansedPostalCode = cleansedPostalCode;
    return this;
  }

   /**
   * The cleansed postal code is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedPostalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "63368-7929", value = "The cleansed postal code is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedPostalCode() {
    return cleansedPostalCode;
  }


  public void setCleansedPostalCode(String cleansedPostalCode) {
    this.cleansedPostalCode = cleansedPostalCode;
  }


  public PlaceInfo cleansedStateProvinceCode(String cleansedStateProvinceCode) {
    
    this.cleansedStateProvinceCode = cleansedStateProvinceCode;
    return this;
  }

   /**
   * The cleansed state is provided by Mastercard matching its transaction data with another Data Partner
   * @return cleansedStateProvinceCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "MO", value = "The cleansed state is provided by Mastercard matching its transaction data with another Data Partner")

  public String getCleansedStateProvinceCode() {
    return cleansedStateProvinceCode;
  }


  public void setCleansedStateProvinceCode(String cleansedStateProvinceCode) {
    this.cleansedStateProvinceCode = cleansedStateProvinceCode;
  }


  public PlaceInfo cleansedStreetAddress(String cleansedStreetAddress) {
    
    this.cleansedStreetAddress = cleansedStreetAddress;
    return this;
  }

   /**
   * The cleansed street address is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedStreetAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2254 HIGHWAY K", value = "The cleansed street address is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedStreetAddress() {
    return cleansedStreetAddress;
  }


  public void setCleansedStreetAddress(String cleansedStreetAddress) {
    this.cleansedStreetAddress = cleansedStreetAddress;
  }


  public PlaceInfo cleansedTelephoneNumber(String cleansedTelephoneNumber) {
    
    this.cleansedTelephoneNumber = cleansedTelephoneNumber;
    return this;
  }

   /**
   * The cleansed telephone number is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization
   * @return cleansedTelephoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "6362814068", value = "The cleansed telephone number is provided by Mastercard matching its transaction data with another Data Partner to ensure standardization")

  public String getCleansedTelephoneNumber() {
    return cleansedTelephoneNumber;
  }


  public void setCleansedTelephoneNumber(String cleansedTelephoneNumber) {
    this.cleansedTelephoneNumber = cleansedTelephoneNumber;
  }


  public PlaceInfo countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * The country code for the desired location
   * @return countryCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "US", required = true, value = "The country code for the desired location")

  public String getCountryCode() {
    return countryCode;
  }


  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public PlaceInfo firstSeenWeek(String firstSeenWeek) {
    
    this.firstSeenWeek = firstSeenWeek;
    return this;
  }

   /**
   * Week of the year for the first transaction
   * @return firstSeenWeek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "04/08/2019-04/14/2019", value = "Week of the year for the first transaction")

  public String getFirstSeenWeek() {
    return firstSeenWeek;
  }


  public void setFirstSeenWeek(String firstSeenWeek) {
    this.firstSeenWeek = firstSeenWeek;
  }


  public PlaceInfo lastSeenWeek(String lastSeenWeek) {
    
    this.lastSeenWeek = lastSeenWeek;
    return this;
  }

   /**
   * Week of the year for the last transaction
   * @return lastSeenWeek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "03/30/2020-04/05/2020", value = "Week of the year for the last transaction")

  public String getLastSeenWeek() {
    return lastSeenWeek;
  }


  public void setLastSeenWeek(String lastSeenWeek) {
    this.lastSeenWeek = lastSeenWeek;
  }


  public PlaceInfo dmaCode(String dmaCode) {
    
    this.dmaCode = dmaCode;
    return this;
  }

   /**
   * A Designated Market Area or a DMA is a geographic  area that  represents specific television markets as defined by and updated annually by the Nielsen Company. (US Only)
   * @return dmaCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "609", value = "A Designated Market Area or a DMA is a geographic  area that  represents specific television markets as defined by and updated annually by the Nielsen Company. (US Only)")

  public String getDmaCode() {
    return dmaCode;
  }


  public void setDmaCode(String dmaCode) {
    this.dmaCode = dmaCode;
  }


  public PlaceInfo geocodeQualityIndicator(String geocodeQualityIndicator) {
    
    this.geocodeQualityIndicator = geocodeQualityIndicator;
    return this;
  }

   /**
   * Geocoding quality indicating the specificity of the geo location such as Storefront, Rooftop, Street, Postcode, Admin, Other or None
   * @return geocodeQualityIndicator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "STOREFRONT", value = "Geocoding quality indicating the specificity of the geo location such as Storefront, Rooftop, Street, Postcode, Admin, Other or None")

  public String getGeocodeQualityIndicator() {
    return geocodeQualityIndicator;
  }


  public void setGeocodeQualityIndicator(String geocodeQualityIndicator) {
    this.geocodeQualityIndicator = geocodeQualityIndicator;
  }


  public PlaceInfo hasCashBack(Boolean hasCashBack) {
    
    this.hasCashBack = hasCashBack;
    return this;
  }

   /**
   * Indicates if the merchants provides cash back
   * @return hasCashBack
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if the merchants provides cash back")

  public Boolean getHasCashBack() {
    return hasCashBack;
  }


  public void setHasCashBack(Boolean hasCashBack) {
    this.hasCashBack = hasCashBack;
  }


  public PlaceInfo hasNfc(Boolean hasNfc) {
    
    this.hasNfc = hasNfc;
    return this;
  }

   /**
   * Indicates if the merchant supports near field communications (nfc)
   * @return hasNfc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if the merchant supports near field communications (nfc)")

  public Boolean getHasNfc() {
    return hasNfc;
  }


  public void setHasNfc(Boolean hasNfc) {
    this.hasNfc = hasNfc;
  }


  public PlaceInfo hasPayAtThePump(Boolean hasPayAtThePump) {
    
    this.hasPayAtThePump = hasPayAtThePump;
    return this;
  }

   /**
   * Indicates if a merchant has pay at the pump
   * @return hasPayAtThePump
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if a merchant has pay at the pump")

  public Boolean getHasPayAtThePump() {
    return hasPayAtThePump;
  }


  public void setHasPayAtThePump(Boolean hasPayAtThePump) {
    this.hasPayAtThePump = hasPayAtThePump;
  }


  public PlaceInfo industry(String industry) {
    
    this.industry = industry;
    return this;
  }

   /**
   * The industry for the desired location
   * @return industry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "SHS", value = "The industry for the desired location")

  public String getIndustry() {
    return industry;
  }


  public void setIndustry(String industry) {
    this.industry = industry;
  }


  public PlaceInfo isInBusiness180Day(Boolean isInBusiness180Day) {
    
    this.isInBusiness180Day = isInBusiness180Day;
    return this;
  }

   /**
   * Indicates if this location was in business in the last 180 days
   * @return isInBusiness180Day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if this location was in business in the last 180 days")

  public Boolean getIsInBusiness180Day() {
    return isInBusiness180Day;
  }


  public void setIsInBusiness180Day(Boolean isInBusiness180Day) {
    this.isInBusiness180Day = isInBusiness180Day;
  }


  public PlaceInfo isInBusiness30Day(Boolean isInBusiness30Day) {
    
    this.isInBusiness30Day = isInBusiness30Day;
    return this;
  }

   /**
   * Indicates if this location was in business in the last 30 days
   * @return isInBusiness30Day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if this location was in business in the last 30 days")

  public Boolean getIsInBusiness30Day() {
    return isInBusiness30Day;
  }


  public void setIsInBusiness30Day(Boolean isInBusiness30Day) {
    this.isInBusiness30Day = isInBusiness30Day;
  }


  public PlaceInfo isInBusiness360Day(Boolean isInBusiness360Day) {
    
    this.isInBusiness360Day = isInBusiness360Day;
    return this;
  }

   /**
   * Indicates if this location was in business in the last in the last 360 days
   * @return isInBusiness360Day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if this location was in business in the last in the last 360 days")

  public Boolean getIsInBusiness360Day() {
    return isInBusiness360Day;
  }


  public void setIsInBusiness360Day(Boolean isInBusiness360Day) {
    this.isInBusiness360Day = isInBusiness360Day;
  }


  public PlaceInfo isInBusiness60Day(Boolean isInBusiness60Day) {
    
    this.isInBusiness60Day = isInBusiness60Day;
    return this;
  }

   /**
   * Indicates if this location was in business in the last 60 days
   * @return isInBusiness60Day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if this location was in business in the last 60 days")

  public Boolean getIsInBusiness60Day() {
    return isInBusiness60Day;
  }


  public void setIsInBusiness60Day(Boolean isInBusiness60Day) {
    this.isInBusiness60Day = isInBusiness60Day;
  }


  public PlaceInfo isInBusiness7Day(Boolean isInBusiness7Day) {
    
    this.isInBusiness7Day = isInBusiness7Day;
    return this;
  }

   /**
   * Indicates if this location was in business in the last 7 days
   * @return isInBusiness7Day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if this location was in business in the last 7 days")

  public Boolean getIsInBusiness7Day() {
    return isInBusiness7Day;
  }


  public void setIsInBusiness7Day(Boolean isInBusiness7Day) {
    this.isInBusiness7Day = isInBusiness7Day;
  }


  public PlaceInfo isInBusiness90Day(Boolean isInBusiness90Day) {
    
    this.isInBusiness90Day = isInBusiness90Day;
    return this;
  }

   /**
   * Indicates if this location was in business in the last 90 days
   * @return isInBusiness90Day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if this location was in business in the last 90 days")

  public Boolean getIsInBusiness90Day() {
    return isInBusiness90Day;
  }


  public void setIsInBusiness90Day(Boolean isInBusiness90Day) {
    this.isInBusiness90Day = isInBusiness90Day;
  }


  public PlaceInfo isNewBusiness(Boolean isNewBusiness) {
    
    this.isNewBusiness = isNewBusiness;
    return this;
  }

   /**
   * Indicates if new or recently opened businesses
   * @return isNewBusiness
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Indicates if new or recently opened businesses")

  public Boolean getIsNewBusiness() {
    return isNewBusiness;
  }


  public void setIsNewBusiness(Boolean isNewBusiness) {
    this.isNewBusiness = isNewBusiness;
  }


  public PlaceInfo keyAggregateMerchantId(Long keyAggregateMerchantId) {
    
    this.keyAggregateMerchantId = keyAggregateMerchantId;
    return this;
  }

   /**
   * The Mastercard defined key aggregate merchant id joins together different channels of one merchant under the same id
   * @return keyAggregateMerchantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12077", value = "The Mastercard defined key aggregate merchant id joins together different channels of one merchant under the same id")

  public Long getKeyAggregateMerchantId() {
    return keyAggregateMerchantId;
  }


  public void setKeyAggregateMerchantId(Long keyAggregateMerchantId) {
    this.keyAggregateMerchantId = keyAggregateMerchantId;
  }


  public PlaceInfo latitude(Double latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * The latitude geo coordinate position of this merchant location up to 6 decimal precision digits
   * @return latitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "38.778083", value = "The latitude geo coordinate position of this merchant location up to 6 decimal precision digits")

  public Double getLatitude() {
    return latitude;
  }


  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }


  public PlaceInfo legalCorporateName(String legalCorporateName) {
    
    this.legalCorporateName = legalCorporateName;
    return this;
  }

   /**
   * The legal corporate name for the desired location
   * @return legalCorporateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "BROWN SHOE COMPANY INC", value = "The legal corporate name for the desired location")

  public String getLegalCorporateName() {
    return legalCorporateName;
  }


  public void setLegalCorporateName(String legalCorporateName) {
    this.legalCorporateName = legalCorporateName;
  }


  public PlaceInfo locationId(Long locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * The Mastercard assigned location id representing this merchant location
   * @return locationId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "300945305", required = true, value = "The Mastercard assigned location id representing this merchant location")

  public Long getLocationId() {
    return locationId;
  }


  public void setLocationId(Long locationId) {
    this.locationId = locationId;
  }


  public PlaceInfo longitude(Double longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * The longitude geo coordinate position of this merchant location up to 6 decimal precision digits
   * @return longitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "-90.699706", value = "The longitude geo coordinate position of this merchant location up to 6 decimal precision digits")

  public Double getLongitude() {
    return longitude;
  }


  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }


  public PlaceInfo mccCode(String mccCode) {
    
    this.mccCode = mccCode;
    return this;
  }

   /**
   * The Merchant Category Code for the desired location
   * @return mccCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5661", value = "The Merchant Category Code for the desired location")

  public String getMccCode() {
    return mccCode;
  }


  public void setMccCode(String mccCode) {
    this.mccCode = mccCode;
  }


  public PlaceInfo merchantName(String merchantName) {
    
    this.merchantName = merchantName;
    return this;
  }

   /**
   * The merchant name for the desired location
   * @return merchantName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "FAMOUSFOOTWEAR#1749", value = "The merchant name for the desired location")

  public String getMerchantName() {
    return merchantName;
  }


  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }


  public PlaceInfo msaCode(String msaCode) {
    
    this.msaCode = msaCode;
    return this;
  }

   /**
   * The metropolitan statistical area (US only). These codes group merchants into metropolitan area
   * @return msaCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7040", value = "The metropolitan statistical area (US only). These codes group merchants into metropolitan area")

  public String getMsaCode() {
    return msaCode;
  }


  public void setMsaCode(String msaCode) {
    this.msaCode = msaCode;
  }


  public PlaceInfo naicsCode(String naicsCode) {
    
    this.naicsCode = naicsCode;
    return this;
  }

   /**
   * North American Industry Classification System Code
   * @return naicsCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "448210", value = "North American Industry Classification System Code")

  public String getNaicsCode() {
    return naicsCode;
  }


  public void setNaicsCode(String naicsCode) {
    this.naicsCode = naicsCode;
  }


  public PlaceInfo parentAggregateMerchantId(String parentAggregateMerchantId) {
    
    this.parentAggregateMerchantId = parentAggregateMerchantId;
    return this;
  }

   /**
   * The ID code for the parent aggregate merchant of this merchant location. This helps to further aggregate merchants under one identifier
   * @return parentAggregateMerchantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10002109", value = "The ID code for the parent aggregate merchant of this merchant location. This helps to further aggregate merchants under one identifier")

  public String getParentAggregateMerchantId() {
    return parentAggregateMerchantId;
  }


  public void setParentAggregateMerchantId(String parentAggregateMerchantId) {
    this.parentAggregateMerchantId = parentAggregateMerchantId;
  }


  public PlaceInfo parentAggregateMerchantName(String parentAggregateMerchantName) {
    
    this.parentAggregateMerchantName = parentAggregateMerchantName;
    return this;
  }

   /**
   * The name for the parent aggregate merchant of this merchant location. This helps to further aggregate merchants under one identifier
   * @return parentAggregateMerchantName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CALERES INC", value = "The name for the parent aggregate merchant of this merchant location. This helps to further aggregate merchants under one identifier")

  public String getParentAggregateMerchantName() {
    return parentAggregateMerchantName;
  }


  public void setParentAggregateMerchantName(String parentAggregateMerchantName) {
    this.parentAggregateMerchantName = parentAggregateMerchantName;
  }


  public PlaceInfo postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The postal code for the desired location
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "63368", value = "The postal code for the desired location")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public PlaceInfo primaryChannelOfDistribution(String primaryChannelOfDistribution) {
    
    this.primaryChannelOfDistribution = primaryChannelOfDistribution;
    return this;
  }

   /**
   * Return businesses that utilize Brick and Mortar or Web as their primary channel. \\r\\nO &#x3D; Online - Ecommerce, B &#x3D; Brick and Mortar, N &#x3D; Non-Store Retail
   * @return primaryChannelOfDistribution
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "B", value = "Return businesses that utilize Brick and Mortar or Web as their primary channel. \\r\\nO = Online - Ecommerce, B = Brick and Mortar, N = Non-Store Retail")

  public String getPrimaryChannelOfDistribution() {
    return primaryChannelOfDistribution;
  }


  public void setPrimaryChannelOfDistribution(String primaryChannelOfDistribution) {
    this.primaryChannelOfDistribution = primaryChannelOfDistribution;
  }


  public PlaceInfo stateProvinceCode(String stateProvinceCode) {
    
    this.stateProvinceCode = stateProvinceCode;
    return this;
  }

   /**
   * The state for the desired location
   * @return stateProvinceCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "MO", value = "The state for the desired location")

  public String getStateProvinceCode() {
    return stateProvinceCode;
  }


  public void setStateProvinceCode(String stateProvinceCode) {
    this.stateProvinceCode = stateProvinceCode;
  }


  public PlaceInfo streetAddress(String streetAddress) {
    
    this.streetAddress = streetAddress;
    return this;
  }

   /**
   * The street address for the desired location
   * @return streetAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2254 HWY K", value = "The street address for the desired location")

  public String getStreetAddress() {
    return streetAddress;
  }


  public void setStreetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
  }


  public PlaceInfo superIndustry(String superIndustry) {
    
    this.superIndustry = superIndustry;
    return this;
  }

   /**
   * The super industry for the desired location
   * @return superIndustry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "AAP", value = "The super industry for the desired location")

  public String getSuperIndustry() {
    return superIndustry;
  }


  public void setSuperIndustry(String superIndustry) {
    this.superIndustry = superIndustry;
  }


  public PlaceInfo telephoneNumber(String telephoneNumber) {
    
    this.telephoneNumber = telephoneNumber;
    return this;
  }

   /**
   * The telephone number for the desired location
   * @return telephoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "6362814068", value = "The telephone number for the desired location")

  public String getTelephoneNumber() {
    return telephoneNumber;
  }


  public void setTelephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaceInfo placeInfo = (PlaceInfo) o;
    return Objects.equals(this.aggregateMerchantId, placeInfo.aggregateMerchantId) &&
        Objects.equals(this.aggregateMerchantName, placeInfo.aggregateMerchantName) &&
        Objects.equals(this.cityName, placeInfo.cityName) &&
        Objects.equals(this.cleansedCityName, placeInfo.cleansedCityName) &&
        Objects.equals(this.cleansedCountryCode, placeInfo.cleansedCountryCode) &&
        Objects.equals(this.cleansedLegalCorporateName, placeInfo.cleansedLegalCorporateName) &&
        Objects.equals(this.cleansedMerchantName, placeInfo.cleansedMerchantName) &&
        Objects.equals(this.cleansedPostalCode, placeInfo.cleansedPostalCode) &&
        Objects.equals(this.cleansedStateProvinceCode, placeInfo.cleansedStateProvinceCode) &&
        Objects.equals(this.cleansedStreetAddress, placeInfo.cleansedStreetAddress) &&
        Objects.equals(this.cleansedTelephoneNumber, placeInfo.cleansedTelephoneNumber) &&
        Objects.equals(this.countryCode, placeInfo.countryCode) &&
        Objects.equals(this.firstSeenWeek, placeInfo.firstSeenWeek) &&
        Objects.equals(this.lastSeenWeek, placeInfo.lastSeenWeek) &&
        Objects.equals(this.dmaCode, placeInfo.dmaCode) &&
        Objects.equals(this.geocodeQualityIndicator, placeInfo.geocodeQualityIndicator) &&
        Objects.equals(this.hasCashBack, placeInfo.hasCashBack) &&
        Objects.equals(this.hasNfc, placeInfo.hasNfc) &&
        Objects.equals(this.hasPayAtThePump, placeInfo.hasPayAtThePump) &&
        Objects.equals(this.industry, placeInfo.industry) &&
        Objects.equals(this.isInBusiness180Day, placeInfo.isInBusiness180Day) &&
        Objects.equals(this.isInBusiness30Day, placeInfo.isInBusiness30Day) &&
        Objects.equals(this.isInBusiness360Day, placeInfo.isInBusiness360Day) &&
        Objects.equals(this.isInBusiness60Day, placeInfo.isInBusiness60Day) &&
        Objects.equals(this.isInBusiness7Day, placeInfo.isInBusiness7Day) &&
        Objects.equals(this.isInBusiness90Day, placeInfo.isInBusiness90Day) &&
        Objects.equals(this.isNewBusiness, placeInfo.isNewBusiness) &&
        Objects.equals(this.keyAggregateMerchantId, placeInfo.keyAggregateMerchantId) &&
        Objects.equals(this.latitude, placeInfo.latitude) &&
        Objects.equals(this.legalCorporateName, placeInfo.legalCorporateName) &&
        Objects.equals(this.locationId, placeInfo.locationId) &&
        Objects.equals(this.longitude, placeInfo.longitude) &&
        Objects.equals(this.mccCode, placeInfo.mccCode) &&
        Objects.equals(this.merchantName, placeInfo.merchantName) &&
        Objects.equals(this.msaCode, placeInfo.msaCode) &&
        Objects.equals(this.naicsCode, placeInfo.naicsCode) &&
        Objects.equals(this.parentAggregateMerchantId, placeInfo.parentAggregateMerchantId) &&
        Objects.equals(this.parentAggregateMerchantName, placeInfo.parentAggregateMerchantName) &&
        Objects.equals(this.postalCode, placeInfo.postalCode) &&
        Objects.equals(this.primaryChannelOfDistribution, placeInfo.primaryChannelOfDistribution) &&
        Objects.equals(this.stateProvinceCode, placeInfo.stateProvinceCode) &&
        Objects.equals(this.streetAddress, placeInfo.streetAddress) &&
        Objects.equals(this.superIndustry, placeInfo.superIndustry) &&
        Objects.equals(this.telephoneNumber, placeInfo.telephoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregateMerchantId, aggregateMerchantName, cityName, cleansedCityName, cleansedCountryCode, cleansedLegalCorporateName, cleansedMerchantName, cleansedPostalCode, cleansedStateProvinceCode, cleansedStreetAddress, cleansedTelephoneNumber, countryCode, firstSeenWeek, lastSeenWeek, dmaCode, geocodeQualityIndicator, hasCashBack, hasNfc, hasPayAtThePump, industry, isInBusiness180Day, isInBusiness30Day, isInBusiness360Day, isInBusiness60Day, isInBusiness7Day, isInBusiness90Day, isNewBusiness, keyAggregateMerchantId, latitude, legalCorporateName, locationId, longitude, mccCode, merchantName, msaCode, naicsCode, parentAggregateMerchantId, parentAggregateMerchantName, postalCode, primaryChannelOfDistribution, stateProvinceCode, streetAddress, superIndustry, telephoneNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaceInfo {\n");
    sb.append("    aggregateMerchantId: ").append(toIndentedString(aggregateMerchantId)).append("\n");
    sb.append("    aggregateMerchantName: ").append(toIndentedString(aggregateMerchantName)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    cleansedCityName: ").append(toIndentedString(cleansedCityName)).append("\n");
    sb.append("    cleansedCountryCode: ").append(toIndentedString(cleansedCountryCode)).append("\n");
    sb.append("    cleansedLegalCorporateName: ").append(toIndentedString(cleansedLegalCorporateName)).append("\n");
    sb.append("    cleansedMerchantName: ").append(toIndentedString(cleansedMerchantName)).append("\n");
    sb.append("    cleansedPostalCode: ").append(toIndentedString(cleansedPostalCode)).append("\n");
    sb.append("    cleansedStateProvinceCode: ").append(toIndentedString(cleansedStateProvinceCode)).append("\n");
    sb.append("    cleansedStreetAddress: ").append(toIndentedString(cleansedStreetAddress)).append("\n");
    sb.append("    cleansedTelephoneNumber: ").append(toIndentedString(cleansedTelephoneNumber)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    firstSeenWeek: ").append(toIndentedString(firstSeenWeek)).append("\n");
    sb.append("    lastSeenWeek: ").append(toIndentedString(lastSeenWeek)).append("\n");
    sb.append("    dmaCode: ").append(toIndentedString(dmaCode)).append("\n");
    sb.append("    geocodeQualityIndicator: ").append(toIndentedString(geocodeQualityIndicator)).append("\n");
    sb.append("    hasCashBack: ").append(toIndentedString(hasCashBack)).append("\n");
    sb.append("    hasNfc: ").append(toIndentedString(hasNfc)).append("\n");
    sb.append("    hasPayAtThePump: ").append(toIndentedString(hasPayAtThePump)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    isInBusiness180Day: ").append(toIndentedString(isInBusiness180Day)).append("\n");
    sb.append("    isInBusiness30Day: ").append(toIndentedString(isInBusiness30Day)).append("\n");
    sb.append("    isInBusiness360Day: ").append(toIndentedString(isInBusiness360Day)).append("\n");
    sb.append("    isInBusiness60Day: ").append(toIndentedString(isInBusiness60Day)).append("\n");
    sb.append("    isInBusiness7Day: ").append(toIndentedString(isInBusiness7Day)).append("\n");
    sb.append("    isInBusiness90Day: ").append(toIndentedString(isInBusiness90Day)).append("\n");
    sb.append("    isNewBusiness: ").append(toIndentedString(isNewBusiness)).append("\n");
    sb.append("    keyAggregateMerchantId: ").append(toIndentedString(keyAggregateMerchantId)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    legalCorporateName: ").append(toIndentedString(legalCorporateName)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    mccCode: ").append(toIndentedString(mccCode)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    msaCode: ").append(toIndentedString(msaCode)).append("\n");
    sb.append("    naicsCode: ").append(toIndentedString(naicsCode)).append("\n");
    sb.append("    parentAggregateMerchantId: ").append(toIndentedString(parentAggregateMerchantId)).append("\n");
    sb.append("    parentAggregateMerchantName: ").append(toIndentedString(parentAggregateMerchantName)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    primaryChannelOfDistribution: ").append(toIndentedString(primaryChannelOfDistribution)).append("\n");
    sb.append("    stateProvinceCode: ").append(toIndentedString(stateProvinceCode)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    superIndustry: ").append(toIndentedString(superIndustry)).append("\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

