/*
 * Places API
 * Places API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.api.places.client;

import com.mastercard.api.places.ApiCallback;
import com.mastercard.api.places.ApiClient;
import com.mastercard.api.places.ApiException;
import com.mastercard.api.places.ApiResponse;
import com.mastercard.api.places.Configuration;
import com.mastercard.api.places.Pair;
import com.mastercard.api.places.ProgressRequestBody;
import com.mastercard.api.places.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mastercard.api.places.model.ErrorResponse;
import com.mastercard.api.places.model.MerchantCategoryCode;
import com.mastercard.api.places.model.PagedMerchantCategoryCode;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MerchantCategoryCodesApi {
    private ApiClient localVarApiClient;

    public MerchantCategoryCodesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MerchantCategoryCodesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for getAllMerchantCategoryCodesUsingGet
     * @param limit Maximum number of items to return. (optional, default to 25)
     * @param offset Number of items to skip before returning the results. (optional, default to 0)
     * @param sort Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by &#39;,&#39;. (optional, default to +merchantCategoryName)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved merchant category codes </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllMerchantCategoryCodesUsingGetCall(Integer limit, Integer offset, String sort, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/merchant-category-codes";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllMerchantCategoryCodesUsingGetValidateBeforeCall(Integer limit, Integer offset, String sort, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = getAllMerchantCategoryCodesUsingGetCall(limit, offset, sort, _callback);
        return localVarCall;

    }

    /**
     * Get all active merchant category codes
     * Returns a list of Merchant Category Codes ordered by Merchant Category Code or Merchant Category Name, depending on user input. The list will be ordered by Merchant Category Name by default.
     * @param limit Maximum number of items to return. (optional, default to 25)
     * @param offset Number of items to skip before returning the results. (optional, default to 0)
     * @param sort Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by &#39;,&#39;. (optional, default to +merchantCategoryName)
     * @return PagedMerchantCategoryCode
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved merchant category codes </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public PagedMerchantCategoryCode getAllMerchantCategoryCodesUsingGet(Integer limit, Integer offset, String sort) throws ApiException {
        ApiResponse<PagedMerchantCategoryCode> localVarResp = getAllMerchantCategoryCodesUsingGetWithHttpInfo(limit, offset, sort);
        return localVarResp.getData();
    }

    /**
     * Get all active merchant category codes
     * Returns a list of Merchant Category Codes ordered by Merchant Category Code or Merchant Category Name, depending on user input. The list will be ordered by Merchant Category Name by default.
     * @param limit Maximum number of items to return. (optional, default to 25)
     * @param offset Number of items to skip before returning the results. (optional, default to 0)
     * @param sort Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by &#39;,&#39;. (optional, default to +merchantCategoryName)
     * @return ApiResponse&lt;PagedMerchantCategoryCode&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved merchant category codes </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PagedMerchantCategoryCode> getAllMerchantCategoryCodesUsingGetWithHttpInfo(Integer limit, Integer offset, String sort) throws ApiException {
        okhttp3.Call localVarCall = getAllMerchantCategoryCodesUsingGetValidateBeforeCall(limit, offset, sort, null);
        Type localVarReturnType = new TypeToken<PagedMerchantCategoryCode>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all active merchant category codes (asynchronously)
     * Returns a list of Merchant Category Codes ordered by Merchant Category Code or Merchant Category Name, depending on user input. The list will be ordered by Merchant Category Name by default.
     * @param limit Maximum number of items to return. (optional, default to 25)
     * @param offset Number of items to skip before returning the results. (optional, default to 0)
     * @param sort Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by &#39;,&#39;. (optional, default to +merchantCategoryName)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved merchant category codes </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Something was wrong with the request. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllMerchantCategoryCodesUsingGetAsync(Integer limit, Integer offset, String sort, final ApiCallback<PagedMerchantCategoryCode> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllMerchantCategoryCodesUsingGetValidateBeforeCall(limit, offset, sort, _callback);
        Type localVarReturnType = new TypeToken<PagedMerchantCategoryCode>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getByMccCodeUsingGET
     * @param mccCode mcc_code (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> This code represents the category that a merchant location may be under and is supported by most payment providers </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> URI didn&#39;t match an existing resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByMccCodeUsingGETCall(String mccCode, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/merchant-category-codes/mcc-codes/{mcc_code}"
            .replaceAll("\\{" + "mcc_code" + "\\}", localVarApiClient.escapeString(mccCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByMccCodeUsingGETValidateBeforeCall(String mccCode, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'mccCode' is set
        if (mccCode == null) {
            throw new ApiException("Missing the required parameter 'mccCode' when calling getByMccCodeUsingGET(Async)");
        }
        

        okhttp3.Call localVarCall = getByMccCodeUsingGETCall(mccCode, _callback);
        return localVarCall;

    }

    /**
     * Get merchant category code by code
     * Get merchant category code by code
     * @param mccCode mcc_code (required)
     * @return MerchantCategoryCode
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> This code represents the category that a merchant location may be under and is supported by most payment providers </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> URI didn&#39;t match an existing resource. </td><td>  -  </td></tr>
     </table>
     */
    public MerchantCategoryCode getByMccCodeUsingGET(String mccCode) throws ApiException {
        ApiResponse<MerchantCategoryCode> localVarResp = getByMccCodeUsingGETWithHttpInfo(mccCode);
        return localVarResp.getData();
    }

    /**
     * Get merchant category code by code
     * Get merchant category code by code
     * @param mccCode mcc_code (required)
     * @return ApiResponse&lt;MerchantCategoryCode&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> This code represents the category that a merchant location may be under and is supported by most payment providers </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> URI didn&#39;t match an existing resource. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MerchantCategoryCode> getByMccCodeUsingGETWithHttpInfo(String mccCode) throws ApiException {
        okhttp3.Call localVarCall = getByMccCodeUsingGETValidateBeforeCall(mccCode, null);
        Type localVarReturnType = new TypeToken<MerchantCategoryCode>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get merchant category code by code (asynchronously)
     * Get merchant category code by code
     * @param mccCode mcc_code (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> This code represents the category that a merchant location may be under and is supported by most payment providers </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication information was missing or invalid. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions for interacting with the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> URI didn&#39;t match an existing resource. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getByMccCodeUsingGETAsync(String mccCode, final ApiCallback<MerchantCategoryCode> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByMccCodeUsingGETValidateBeforeCall(mccCode, _callback);
        Type localVarReturnType = new TypeToken<MerchantCategoryCode>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
